---
- hosts: localhost
  collections:
    - azure.azcollection
  vars:
    ta_tags:
      Function: Digital Channels Shared Channels Experience
      Persistence: mon-fri,07:00-23:00
      Application: Next Generation Contact Centre (current PSN-CC service)
      Role: Test Automation
      Business-Project: PRJ0046377
      Project-Cost-Code: '10389352'
      Environment: "{{ lookup('env','ENVIRONMENT') }}"
      
  roles:
    # - create_sql_resources
    # - create_mongodb_vm
    # - create_xms_vm
    # - create_nuance_vm
